// ballet-school-backend/src/announcement/dto/create-announcement.dto.ts
import { AnnouncementCategory } from '../announcement.entity';

export class CreateAnnouncementDto {
  title: string;
  content: string;
  category: AnnouncementCategory;
  isImportant?: boolean;
  // 'date' will be auto-generated by the database / CreateDateColumn
}
